<?php 
/**
* Configure ACF settings for use in the theme
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_56259c4ab8fa7',
	'title' => 'Display Post in Slider',
	'fields' => array (
		array (
			'key' => 'field_56259c4abc156',
			'label' => '',
			'name' => 'display_post_in_slider',
			'type' => 'true_false',
			'instructions' => 'Check this box to display the current post in the latest posts slider (if enabled)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_562192c7c4305',
	'title' => 'Featured Slider',
	'fields' => array (
		array (
			'key' => 'field_562192c7ca9d7',
			'label' => 'Custom Slides',
			'name' => 'custom_slides',
			'type' => 'repeater',
			'instructions' => 'Create your custom slides here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_562192c7cc3be',
					'label' => 'Slide Image',
					'name' => 'slide_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_562192c7cc3d1',
					'label' => 'Slide Title',
					'name' => 'slide_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_562192c7cc3f7',
					'label' => 'Slide Subtitle',
					'name' => 'slide_subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide subtitle',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_562192c7cc416',
					'label' => 'Slide Link',
					'name' => 'slide_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide link URL',
				),
			),
		),
		array (
			'key' => 'field_56219323e817f',
			'label' => 'Post Slides',
			'name' => 'post_slides',
			'type' => 'relationship',
			'instructions' => 'Select posts to include in the slider',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array (
				0 => 'post',
			),
			'taxonomy' => array (
			),
			'filters' => '',
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'id',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'stnsvn_slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_56201a4c3c5ec',
	'title' => 'Landing Page Template',
	'fields' => array (
		array (
			'key' => 'field_56201aaf75558',
			'label' => 'Featured Slides',
			'name' => 'featured_slides',
			'type' => 'repeater',
			'instructions' => 'Create your landing page slides here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'row',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_56201e7375559',
					'label' => 'Slide Image',
					'name' => 'slide_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_56201eae7555a',
					'label' => 'Slide Title',
					'name' => 'slide_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56201ee07555b',
					'label' => 'Slide Subtitle',
					'name' => 'slide_subtitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide subtitle',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56eb09bdc36c9',
					'label' => 'Button Text',
					'name' => 'slide_button_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide button text',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_56201f207555c',
					'label' => 'Slide Link',
					'name' => 'slide_link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Enter slide link URL',
				),
			),
		),
		array (
			'key' => 'field_56203121619b0',
			'label' => 'Landing Content Sections',
			'name' => 'landing_content_sections',
			'type' => 'flexible_content',
			'instructions' => 'Click "Add Section" to begin adding content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
			'layouts' => array (
				array (
					'key' => '56203133e9ef7',
					'name' => 'text_section',
					'label' => 'Text Section',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_562032963dc90',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Enter section title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56203181619b1',
							'label' => 'Text Content',
							'name' => 'text_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_562032b23dc91',
							'label' => 'Link Button Text',
							'name' => 'link_button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Enter link button text',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_562032e23dc92',
							'label' => 'Link Button URL',
							'name' => 'link_button_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Enter link button URL',
						),
						array (
							'key' => 'field_56bea75494701',
							'label' => 'Section Background Color',
							'name' => 'landing_text_bg',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#f5f5f2',
						),
						array (
							'key' => 'field_5702ec6edebac',
							'label' => 'Section Text Color',
							'name' => 'landing_text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#333333',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56203b421953e',
					'name' => 'image_blocks',
					'label' => 'Image Blocks',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56203b721953f',
							'label' => 'Number of Columns',
							'name' => 'number_of_columns',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								1 => 1,
								2 => 2,
								3 => 3,
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_56203bcb19540',
							'label' => 'Column 1 Image',
							'name' => 'column_1_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56203c2619541',
							'label' => 'Column 1 Text',
							'name' => 'column_1_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_562040d519542',
							'label' => 'Column 1 Link',
							'name' => 'column_1_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5620447b4557a',
							'label' => 'Column 2 Image',
							'name' => 'column_2_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_562044f0fa451',
							'label' => 'Column 2 Text',
							'name' => 'column_2_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_562045493a7b7',
							'label' => 'Column 2 Link',
							'name' => 'column_2_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_562044b64557b',
							'label' => 'Column 3 Image',
							'name' => 'column_3_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_56204512fa452',
							'label' => 'Column 3 Text',
							'name' => 'column_3_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_562045663a7b8',
							'label' => 'Column 3 Link',
							'name' => 'column_3_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_56203b721953f',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_56bea7a994702',
							'label' => 'Section Background Color',
							'name' => 'image_blocks_bg',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#f5f5f2',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '5621767e07a10',
					'name' => 'content_columns',
					'label' => 'Content Columns',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5621767e07a11',
							'label' => 'Number of Content Columns',
							'name' => 'number_of_content_columns',
							'type' => 'select',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								1 => 1,
								2 => 2,
								3 => 3,
							),
							'default_value' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_5621767e07a12',
							'label' => 'Column 1 Content',
							'name' => 'column_1_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5621767e07a13',
							'label' => 'Column 2 Content',
							'name' => 'column_2_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5621767e07a11',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_5621767e07a14',
							'label' => 'Column 3 Content',
							'name' => 'column_3_content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_5621767e07a11',
										'operator' => '==',
										'value' => '3',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56bea7d494703',
							'label' => 'Section Background Color',
							'name' => 'content_columns_bg',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#f5f5f2',
						),
						array (
							'key' => 'field_5702eceb6295e',
							'label' => 'Section Text Color',
							'name' => 'content_columns_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#333333',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '56ecbfe838057',
					'name' => 'latest_posts',
					'label' => 'Latest Posts',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_56ecc0c43805c',
							'label' => 'Content Before Posts',
							'name' => 'latest_content',
							'type' => 'wysiwyg',
							'instructions' => 'Enter any text or content you want to display before the posts.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_56ecc01238058',
							'label' => 'Number of Posts',
							'name' => 'number_of_posts',
							'type' => 'number',
							'instructions' => 'Number of posts to display. Enter "-1" to display all posts.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 3,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_56ecc03538059',
							'label' => 'Categories',
							'name' => 'latest_categories',
							'type' => 'taxonomy',
							'instructions' => 'Limit posts to specific categories',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'category',
							'field_type' => 'multi_select',
							'allow_null' => 1,
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'id',
							'multiple' => 0,
						),
						array (
							'key' => 'field_56ecc06c3805a',
							'label' => 'Background Colour',
							'name' => 'latest_background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#FFFFFF',
						),
						array (
							'key' => 'field_56ecc0943805b',
							'label' => 'Text Colour',
							'name' => 'latest_text_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#333333',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-landing.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'featured_image',
	),
	'active' => 1,
	'description' => '',
));

	acf_add_local_field_group(array (		
	'key' => 'group_56a183b99291e',		
	'title' => __('Select Displayed Category', 'monstera'),		
	'fields' => array (		
		array (		
			'key' => 'field_56a183b9abf78',		
			'label' => __('Select Displayed Category', 'monstera'),		
			'name' => 'displayed_category',		
			'type' => 'taxonomy',		
			'instructions' => __('Select which category is displayed above the title of the post.', 'monstera'),		
			'required' => 0,		
			'conditional_logic' => 0,		
			'wrapper' => array (		
				'width' => '',		
				'class' => '',		
				'id' => '',		
			),		
			'taxonomy' => 'category',		
			'field_type' => 'select',		
			'allow_null' => 1,		
			'add_term' => 0,		
			'save_terms' => 0,		
			'load_terms' => 0,		
			'return_format' => 'id',		
			'multiple' => 0,		
		),		
	),		
	'location' => array (		
		array (		
			array (		
				'param' => 'post_type',		
				'operator' => '==',		
				'value' => 'post',		
			),		
		),		
	),		
	'menu_order' => 0,		
	'position' => 'side',		
	'style' => 'default',		
	'label_placement' => 'top',		
	'instruction_placement' => 'label',		
	'hide_on_screen' => '',		
	'active' => 1,			'active' => 1,
	'description' => '',
	));

endif;
?>